In [1]:
import numpy as np 

In [2]:
X = np.random.randint(0, 100, (10, 4))
X

array([[95, 97, 48, 18],
       [23, 78, 95, 63],
       [13,  1, 54, 48],
       [13, 59, 91, 73],
       [24, 58, 89, 11],
       [61, 98, 37, 82],
       [45, 67, 93, 11],
       [67,  0, 60, 98],
       [35, 49, 56, 12],
       [ 4, 21, 79, 66]])

In [5]:
W = np.random.random_sample((3, 4))
W

array([[0.99635093, 0.74680159, 0.24747198, 0.54020622],
       [0.74421901, 0.31656368, 0.16675469, 0.46000984],
       [0.92180131, 0.78096638, 0.07763363, 0.7283088 ]])

In [7]:
b = np.random.random_sample((3,))

In [9]:
forward_pass = np.matmul(X, W.T) + b
print(f"Shape: {forward_pass.shape}, {forward_pass}")

Shape: (10, 3), [[189.53333683 118.39276348 180.83441498]
 [139.54730275  87.33219848 136.0490363 ]
 [ 53.83062663  41.77751555  52.5890015 ]
 [119.80673757  77.80837826 118.9652156 ]
 [ 96.03206651  56.82410405  83.01365058]
 [188.25521312 121.01220929 196.03193043]
 [124.66653829  75.96879501 109.71070991]
 [135.38191835 105.64979842 138.46654752]
 [ 92.64434328  57.11854516  84.29116671]
 [ 75.71001154  53.85986238  74.96251638]]


In [10]:
W_last = np.random.random_sample((3,))

print( 1 / (1 + (np.exp(-(np.matmul(forward_pass, W_last))))))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
