In [1]:
import numpy as np 
from tensorflow.keras.layers import Dense 

In [12]:
X_sample = np.array([[9, 190], [1, 110]])

W_1 = np.array([
    [0.001, 0.003],
    [0.0014, 0.0035],
    [0.0051, 0.0053]
])


B_1 = np.array([0.004, 0.001, 0.002])


log_layer = Dense(units=3, activation='sigmoid')
log_layer(X_sample)
log_layer.set_weights([W_1.T, B_1])
log_layer.get_weights()

[array([[0.001 , 0.0014, 0.0051],
        [0.003 , 0.0035, 0.0053]], dtype=float32),
 array([0.004, 0.001, 0.002], dtype=float32)]

In [13]:
a1 = log_layer(X_sample)
a1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.64175737, 0.66342616, 0.7417147 ],
       [0.58297545, 0.5956567 , 0.6433881 ]], dtype=float32)>

In [17]:
final_layer = Dense(units=1, activation='sigmoid')
final_layer(a1)
final_layer.set_weights([np.array([0.001, 0.003, 0.002]).reshape(3, 1), np.array([0.0071])])
final_layer(a1)

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[0.50280386],
       [0.5026892 ]], dtype=float32)>