In [1]:
import numpy as np 

In [21]:
X = np.random.randint(10, 3000, size=(100,8)).astype('float')
X

array([[ 389., 1794.,  745., 1211.,  249.,   39.,  770., 1713.],
       [2652.,  942., 2333., 1656.,  958., 1501., 2224., 2932.],
       [1796., 2950., 2077., 2955., 2667., 1365.,  712.,  825.],
       [1519., 1646.,  614.,  881., 1976., 1488., 2305., 2921.],
       [2421.,  150., 1514., 2308., 1086.,  244., 2277.,  323.],
       [2994., 2050., 2557., 1959., 2710.,   16.,  731., 1353.],
       [1717.,   99., 2808., 2040.,  990., 2190.,   78., 2122.],
       [  26., 2671.,  177., 2811.,  328.,  979.,  921.,  448.],
       [ 438., 1106.,  262.,  722.,  858., 1332.,  292., 1847.],
       [ 104.,  261., 2724.,  243.,   92.,  537., 2244., 1814.],
       [2947.,  912.,  249.,  932., 2544., 1649., 1207., 1913.],
       [ 426.,  353., 1786., 1806.,   96., 1542.,  718.,  405.],
       [2914., 1060., 2909., 1647.,  977.,  389.,  694., 1670.],
       [2287., 1117.,  500., 2447.,  772., 1705., 1806., 1431.],
       [1868., 2654.,  783., 2698., 2761.,  904.,  809., 2916.],
       [2289.,  673., 172

### First Strategy: Divide each value by its maximum value. This will result in a range 0 <= x_i => 1

In [22]:
n = X.shape[1]
# X_max = np.zeros((n,))
X_copy = np.copy(X)

for i in range(n):
    max_val = np.max(X_copy[:, i])
    X_copy[:, i] = X_copy[:, i] / max_val

X_copy

array([[0.12992652, 0.60813559, 0.24891413, 0.40447562, 0.08319412,
        0.01308725, 0.25925926, 0.57813027],
       [0.88577154, 0.31932203, 0.77948547, 0.55310621, 0.32008019,
        0.50369128, 0.74882155, 0.98953763],
       [0.5998664 , 1.        , 0.69395256, 0.98697395, 0.89107918,
        0.45805369, 0.23973064, 0.27843402],
       [0.50734803, 0.5579661 , 0.20514534, 0.29425518, 0.66020715,
        0.49932886, 0.77609428, 0.98582518],
       [0.80861723, 0.05084746, 0.50584698, 0.77087508, 0.36284664,
        0.08187919, 0.76666667, 0.10901114],
       [1.        , 0.69491525, 0.85432676, 0.65430862, 0.90544604,
        0.00536913, 0.24612795, 0.45663179],
       [0.57348029, 0.03355932, 0.93818911, 0.68136273, 0.3307718 ,
        0.73489933, 0.02626263, 0.71616605],
       [0.00868403, 0.90542373, 0.05913799, 0.93887776, 0.10958904,
        0.32852349, 0.31010101, 0.15119811],
       [0.14629259, 0.37491525, 0.08753759, 0.24114896, 0.28666889,
        0.44697987, 0.098316

### Second Strategy is Min-Max Normalization (0 - 1 common range)

In [24]:
X_copy = np.copy(X)

for i in range(X_copy.shape[1]):
    X_max = np.max(X_copy[:, i])
    X_min = np.min(X_copy[:, i])

    X_copy[:, i] = (X_copy[:, i] - X_min) / (X_max - X_min)

X_copy

array([[1.22304582e-01, 5.95096322e-01, 2.43861419e-01, 3.99461098e-01,
        7.85762257e-02, 7.75978408e-03, 2.47091034e-01, 5.74685267e-01],
       [8.84770889e-01, 2.96672504e-01, 7.78002018e-01, 5.49343213e-01,
        3.16655473e-01, 5.01012146e-01, 7.44695414e-01, 9.89452195e-01],
       [5.96361186e-01, 1.00000000e+00, 6.91893710e-01, 9.86864264e-01,
        8.90530557e-01, 4.55128205e-01, 2.27241615e-01, 2.72541681e-01],
       [5.03032345e-01, 5.43257443e-01, 1.99798184e-01, 2.88312563e-01,
        6.58495635e-01, 4.96626181e-01, 7.72416153e-01, 9.85709425e-01],
       [8.06940701e-01, 1.92644483e-02, 5.02522704e-01, 7.68945773e-01,
        3.59637340e-01, 7.69230769e-02, 7.62833676e-01, 1.01735284e-01],
       [1.00000000e+00, 6.84763573e-01, 8.53346788e-01, 6.51397777e-01,
        9.04969778e-01, 0.00000000e+00, 2.33744011e-01, 4.52194624e-01],
       [5.69743935e-01, 1.40105079e-03, 9.37773293e-01, 6.78679690e-01,
        3.27400940e-01, 7.33468286e-01, 1.02669405e-02, 7.

### Third Strategy is Standard Scaling (Z-score normalization) (mean = 0, std = 1)

In [25]:
X_copy = np.copy(X)

for i in range(X_copy.shape[1]):
    X_copy[:, i] = (X_copy[:, i] - np.mean(X_copy[:, i])) / np.std(X_copy[:, i])

X_copy

array([[-1.37179495e+00,  6.04381617e-01, -9.46744726e-01,
        -4.47688996e-01, -1.41040154e+00, -1.75872646e+00,
        -7.60254988e-01,  2.09659755e-01],
       [ 1.22554943e+00, -3.33497477e-01,  8.06833888e-01,
         9.29835233e-02, -6.02217097e-01, -9.82114410e-03,
         9.47417805e-01,  1.60099974e+00],
       [ 2.43080674e-01,  1.87690302e+00,  5.24141114e-01,
         1.67126128e+00,  1.34586077e+00, -1.72510011e-01,
        -8.28373985e-01, -8.03884055e-01],
       [-7.48443777e-02,  4.41463652e-01, -1.09140392e+00,
        -8.48637156e-01,  5.58194413e-01, -2.53722858e-02,
         1.04254951e+00,  1.58844458e+00],
       [ 9.60420593e-01, -1.20532875e+00, -9.75621351e-02,
         8.85159888e-01, -4.56310738e-01, -1.51349692e+00,
         1.00966447e+00, -1.37685589e+00],
       [ 1.61807783e+00,  8.86185664e-01,  1.05419007e+00,
         4.61126834e-01,  1.39487619e+00, -1.78624002e+00,
        -8.06059141e-01, -2.01236384e-01],
       [ 1.52408908e-01, -1.261469

In [28]:
print(f"Mean: {np.mean(X_copy[:, 0])}, Std: {X_copy[:, 0]}")

Mean: 2.4424906541753444e-17, Std: [[-1.37179495e+00  6.04381617e-01 -9.46744726e-01 -4.47688996e-01
  -1.41040154e+00 -1.75872646e+00 -7.60254988e-01  2.09659755e-01]
 [ 1.22554943e+00 -3.33497477e-01  8.06833888e-01  9.29835233e-02
  -6.02217097e-01 -9.82114410e-03  9.47417805e-01  1.60099974e+00]
 [ 2.43080674e-01  1.87690302e+00  5.24141114e-01  1.67126128e+00
   1.34586077e+00 -1.72510011e-01 -8.28373985e-01 -8.03884055e-01]
 [-7.48443777e-02  4.41463652e-01 -1.09140392e+00 -8.48637156e-01
   5.58194413e-01 -2.53722858e-02  1.04254951e+00  1.58844458e+00]
 [ 9.60420593e-01 -1.20532875e+00 -9.75621351e-02  8.85159888e-01
  -4.56310738e-01 -1.51349692e+00  1.00966447e+00 -1.37685589e+00]
 [ 1.61807783e+00  8.86185664e-01  1.05419007e+00  4.61126834e-01
   1.39487619e+00 -1.78624002e+00 -8.06059141e-01 -2.01236384e-01]
 [ 1.52408908e-01 -1.26146940e+00  1.33136150e+00  5.59541382e-01
  -5.65740508e-01  8.14389366e-01 -1.57298509e+00  6.76483424e-01]
 [-1.78842597e+00  1.56978064e+00 

In [31]:
print(X)
print(X.T)

[[ 389. 1794.  745. 1211.  249.   39.  770. 1713.]
 [2652.  942. 2333. 1656.  958. 1501. 2224. 2932.]
 [1796. 2950. 2077. 2955. 2667. 1365.  712.  825.]
 [1519. 1646.  614.  881. 1976. 1488. 2305. 2921.]
 [2421.  150. 1514. 2308. 1086.  244. 2277.  323.]
 [2994. 2050. 2557. 1959. 2710.   16.  731. 1353.]
 [1717.   99. 2808. 2040.  990. 2190.   78. 2122.]
 [  26. 2671.  177. 2811.  328.  979.  921.  448.]
 [ 438. 1106.  262.  722.  858. 1332.  292. 1847.]
 [ 104.  261. 2724.  243.   92.  537. 2244. 1814.]
 [2947.  912.  249.  932. 2544. 1649. 1207. 1913.]
 [ 426.  353. 1786. 1806.   96. 1542.  718.  405.]
 [2914. 1060. 2909. 1647.  977.  389.  694. 1670.]
 [2287. 1117.  500. 2447.  772. 1705. 1806. 1431.]
 [1868. 2654.  783. 2698. 2761.  904.  809. 2916.]
 [2289.  673. 1722. 2229. 1794.  521.  664.  960.]
 [2216. 1784.  573.  168.  307.  282.  810. 1892.]
 [ 256.  722. 1877. 1893. 2207. 2346. 1847.  997.]
 [2547. 1956. 2031. 1290.  998. 1625.  266. 1780.]
 [2548.  119.  885.  396. 1388.