In [3]:
import numpy as np 
import copy, math
import matplotlib.pyplot as plt 

In [4]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [5]:
print(f"X_train.shape: {X_train.shape}")
print(X_train)
print(f"y_train.shape: {y_train.shape}")
print(y_train)

X_train.shape: (3, 4)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y_train.shape: (3,)
[460 232 178]


In [6]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [7]:
def predict_loop(X, w, b):
    '''
    Predict loop using linear regression. Loop over individual instance. No vectorization.

    Args:
        X (ndarray): Shape(m,n) m examples of n vectors.
        w (ndarray): Shape(n,) m weights for corresponding feature values.
        b (float): model parameter
    
    Returns: 
        y_hat (ndarray): Shape (m,) predicted outputs for m examples.
    '''
    m, n = X.shape

    y_hat = np.zeros((m,))

    for i in range(m):
        for j in range(n):
            y_hat[i] = y_hat[i] + (w[j] * X[i, j])
    
        y_hat[i] += b

    return y_hat

In [10]:
predict_loop(X_train, w_init, b_init)

array([459.99999762, 231.99999837, 177.99999899])

In [11]:
def predict(X, w, b):
    ''' 
    Predict with vectorization.
    Args:
        X (ndarray): Shape(m,n) m examples of n vectors.
        w (ndarray): Shape(n,) m weights for corresponding feature values.
        b (float): model parameter

    Returns: 
        y_hat (ndarray): Shape (m,) predicted outputs for m examples.   
    '''

    y_hat = np.dot(X, w) + b
    return y_hat

In [12]:
predict(X_train, w_init, b_init)

array([459.99999762, 231.99999837, 177.99999899])

In [15]:
def compute_cost(X, y, w, b):
    ''' 
    Compute cost for multiple regression with vectorization.
    Args:
        X (ndarray): Shape(m,n) m examples of n vectors.
        y (ndarray): m target values.
        w (ndarray): Shape(n,) m weights for corresponding feature values.
        b (float): model parameter

    Returns: 
        total_cost (float): Computed cost for m examples based on the given w and b.   
    '''
    m = X.shape[0]
    y_hat = predict(X, w, b)
    total_cost = (1/(2*m)) * np.sum((y_hat - y) ** 2)
    return total_cost

In [16]:
print(f"Cost: {compute_cost(X_train, y_train, w_init, b_init)}, w: {w_init}, b: {b_init}")

Cost: 1.5578903428073909e-12, w: [  0.39133535  18.75376741 -53.36032453 -26.42131618], b: 785.1811367994083


In [19]:
def compute_gradients(X, y, w, b):
    m, n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.0 

    for i in range(n):
        dj_dw[i] = (1/m) * np.sum((predict(X, w, b) - y) * X[:, i])

    dj_db = (1/m) * np.sum(predict(X, w, b) - y)

    return dj_dw, dj_db

In [20]:
compute_gradients(X_train, y_train, w_init, b_init)

(array([-2.72623569e-03, -6.27197244e-06, -2.21745567e-06, -6.92403362e-05]),
 -1.6739250744042995e-06)